DELETE http://localhost:3100/api/blogs/60ce6359b27f171844ffdf54 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyTmFtZSI6Iml6aWQiLCJpZCI6IjYwY2RkMGEzMTUyOGI5MDE3ZTM1YTk4YSIsImlhdCI6MTYyNDEzOTkwNn0.aRFb3VB3O60BMzvw46NEFuE8C_W7pzYfapuzcxkMnEo